# Generated by Django 2.2.7 on 2019-12-04 16:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=100)),
                ('shopLocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('shopAddress', models.CharField(max_length=200)),
                ('shopCity', models.CharField(max_length=100)),
            ],
        ),
    ]
