# Generated by Django 2.2.7 on 2019-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopAddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopCity',
            field=models.CharField(max_length=50),
        ),
    ]
