# Generated by Django 2.2.7 on 2019-12-04 16:11

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'data.json'


def load_data(apps, schema_editor):
    Shop = apps.get_model('WebMap', 'Shop')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile),encoding='UTF-8') as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    shopName = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    shopLocation = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    housename = tags.get('addr:housename', 'no house name')
                    street = tags.get('addr:street','no street name')
                    city = tags.get('addr:city','no city name')
                    address= housename + ',' + street
                    Shop(shopName=shopName, shopLocation=shopLocation, shopAddress=address, shopCity=city).save()
            except KeyError:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ('WebMap', '0002_auto_20191204_1611'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]