# Generated by Django 2.2.7 on 2019-12-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebMap', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userpassword',
        ),
    ]
